clc;
clear;
X=-9:0.2:9;
MU=0;
SIGMA=sqrt(1);
f1 = normpdf(X,MU,SIGMA);
MU=1;
SIGMA=sqrt(1);
f2 = normpdf(X,MU,SIGMA);
MU=2;
SIGMA=sqrt(1);
f3 = normpdf(X,MU,SIGMA);
a = 1/3;
f4 = f1 + f2 + f3;
plot(X,f1,X,f2,'.',X,f3,'+',X,f4,'--');